apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/baffold/baffold-java
    workspace: .
    bazel:
      target: //baffold-java:baffold-java.tar
  - imageName: gcr.io/baffold/baffold-go
    workspace: .
    bazel:
      target: //baffold-go:baffold-go.tar
  local: {}
deploy:
  kubectl:
    manifests:
      - baffold-k8s/sub/pod-*.yaml